apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    name: app
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 3000
  selector:
    name: app
  type: LoadBalancer
  loadBalancerIP: "YOUR.IP.ADDRESS.HERE"  
status:
  loadBalancer: {}
